// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdbQDnHPU6YStWu499_fqIXIO_6g90VNg',
    appId: '1:780302459736:web:263d68089c0a34d6e4fb2d',
    messagingSenderId: '780302459736',
    projectId: 'hushxtinder',
    authDomain: 'hushxtinder.firebaseapp.com',
    storageBucket: 'hushxtinder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7MVIeqKN8fI_cB9DdzWbcKRZ6PdNcfUs',
    appId: '1:780302459736:android:23b3b15b45972f7ae4fb2d',
    messagingSenderId: '780302459736',
    projectId: 'hushxtinder',
    storageBucket: 'hushxtinder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgF3KT0ojDzgC24VZYiutWrRCUg_EUJlQ',
    appId: '1:780302459736:ios:3247817b67676b83e4fb2d',
    messagingSenderId: '780302459736',
    projectId: 'hushxtinder',
    storageBucket: 'hushxtinder.appspot.com',
    iosBundleId: 'com.example.hushhxtinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgF3KT0ojDzgC24VZYiutWrRCUg_EUJlQ',
    appId: '1:780302459736:ios:3247817b67676b83e4fb2d',
    messagingSenderId: '780302459736',
    projectId: 'hushxtinder',
    storageBucket: 'hushxtinder.appspot.com',
    iosBundleId: 'com.example.hushhxtinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdbQDnHPU6YStWu499_fqIXIO_6g90VNg',
    appId: '1:780302459736:web:2c99ad036757bd8de4fb2d',
    messagingSenderId: '780302459736',
    projectId: 'hushxtinder',
    authDomain: 'hushxtinder.firebaseapp.com',
    storageBucket: 'hushxtinder.appspot.com',
  );
}
